name: Run LekScrape Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Create Google Docs auth JSON
        uses: jsdaniell/create-json@v.1.2.3
        with:
          name: "google-auth-file.json"
          json: ${{secrets.GOOGLE_API_JSON}}

      - name: Fetch dependencies
        run: go get github.com/jacksondarman/lekscraper

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        env:
          GOOGLE_CREDENTIALS_FILE_PATH: ${{secrets.GOOGLE_API_JSON}}
          DOCUMENT_ID: ${{secrets.DOCUMENT_ID}}
