name: vuln

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]
  schedule:
    - cron: "0 10 * * 1"

jobs:
  run:
    name: Vuln
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"
          check-latest: true

      - name: Install Go Dependencies
        run: go get ./...

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck -test ./...
